services:
  jse-sens-ai:
    build: 
      context: './jse-sens-bot'
      # dockerfile: './Docker/Dockerfile'
    command: ["python", "app.py"]
    ports:
      - 8000:8000

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      # - /etc/letsencrypt:/etc/letsencrypt
      # - /var/www/certbot:/var/www/certbot
    depends_on:
      - jse-sens-ai